[package]
name = "rustic_gl"
version = "0.3.2"
authors = ["shivshank"]
description = "Utilities for working with OpenGL directly"

license = "MIT"

keywords = ["OpenGL"]
repository = "https://github.com/shivshank/rustic_gl"

[dependencies]
gl = "0.10.0"
